apiVersion: v1
kind: Namespace
metadata:
  name: pokedex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-pokedex
  namespace: pokedex
  labels:
    app: modern-pokedex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modern-pokedex
  template:
    metadata:
      labels:
        app: modern-pokedex
    spec:
      containers:
      - name: modern-pokedex
        image: chakorn/modern-pokedex:1.0.6
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: pokedex-configmap
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: modern-pokedex-service
  namespace: pokedex
spec:
  type: NodePort
  selector:
    app: modern-pokedex
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pokedex-configmap
  namespace: pokedex
data:
  API_BASE_URL: "http://localhost:30001"
  VITE_API_BASE_URL: "http://localhost:30001/api"
  VITE_APP_TITLE: "Modern Pokédex"
  VITE_APP_VERSION: "1.0.0"
