apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml

commonLabels:
  app: modern-pokedex
  version: v1.0.0

images:
- name: modern-pokedex
  newTag: latest