apiVersion: v1
kind: Namespace
metadata:
  name: pokedex
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pokedex-configmap
  namespace: pokedex
data:
  # For localhost development
  LOCALHOST_API_BASE_URL: "http://localhost:30001"
  LOCALHOST_VITE_API_BASE_URL: "http://localhost:30001/api"
  
  # For server deployment (27.254.134.143)
  SERVER_API_BASE_URL: "http://27.254.134.143:30001"
  SERVER_VITE_API_BASE_URL: "http://27.254.134.143:30001/api"
  
  # App configuration
  VITE_APP_TITLE: "Modern Pokédex"
  VITE_APP_VERSION: "1.0.6"
  
  # Environment
  NODE_ENV: "production"
  GO_ENV: "production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-backend
  namespace: pokedex
  labels:
    app: pokedex-backend
    version: "1.0.6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-backend
  template:
    metadata:
      labels:
        app: pokedex-backend
        version: "1.0.6"
    spec:
      containers:
      - name: pokedex-backend
        image: chakorn/pokedex-backend:1.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: GO_ENV
          valueFrom:
            configMapKeyRef:
              name: pokedex-configmap
              key: GO_ENV
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/pokemon/stats
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/pokemon/stats
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/pokemon/stats
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-backend-service
  namespace: pokedex
  labels:
    app: pokedex-backend
spec:
  type: NodePort
  selector:
    app: pokedex-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-pokedex
  namespace: pokedex
  labels:
    app: modern-pokedex
    version: "1.0.6"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: modern-pokedex
  template:
    metadata:
      labels:
        app: modern-pokedex
        version: "1.0.6"
    spec:
      containers:
      - name: modern-pokedex
        image: chakorn/modern-pokedex:1.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        # Use server configuration for production
        - name: VITE_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: pokedex-configmap
              key: SERVER_VITE_API_BASE_URL
        - name: VITE_APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: pokedex-configmap
              key: VITE_APP_TITLE
        - name: VITE_APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: pokedex-configmap
              key: VITE_APP_VERSION
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: modern-pokedex-service
  namespace: pokedex
  labels:
    app: modern-pokedex
spec:
  type: NodePort
  selector:
    app: modern-pokedex
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30000
      protocol: TCP
