apiVersion: v1
kind: Namespace
metadata:
  name: pokedex-local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pokedex-configmap-local
  namespace: pokedex-local
data:
  # For localhost development
  VITE_API_BASE_URL: "http://localhost:30001/api"
  VITE_APP_TITLE: "Modern Pokédex (Local)"
  VITE_APP_VERSION: "1.0.6-local"
  NODE_ENV: "development"
  GO_ENV: "development"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-backend-local
  namespace: pokedex-local
  labels:
    app: pokedex-backend-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-backend-local
  template:
    metadata:
      labels:
        app: pokedex-backend-local
    spec:
      containers:
      - name: pokedex-backend
        image: chakorn/pokedex-backend:local1.0.6
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 8080
        env:
        - name: GO_ENV
          value: "development"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/pokemon/stats
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/pokemon/stats
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-backend-service-local
  namespace: pokedex-local
spec:
  type: NodePort
  selector:
    app: pokedex-backend-local
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-pokedex-local
  namespace: pokedex-local
  labels:
    app: modern-pokedex-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modern-pokedex-local
  template:
    metadata:
      labels:
        app: modern-pokedex-local
    spec:
      containers:
      - name: modern-pokedex
        image: chakorn/modern-pokedex:local1.0.6
        imagePullPolicy: Never  # Use local image
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: pokedex-configmap-local
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: modern-pokedex-service-local
  namespace: pokedex-local
spec:
  type: NodePort
  selector:
    app: modern-pokedex-local
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
