# Docker Compose for production deployment
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    volumes: []  # Remove volume mounts for production
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  nginx:
    profiles: []  # Always include nginx in production
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M