apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml

commonLabels:
  app: pokedex-backend
  version: "1.0.0"

namespace: default